[package]
name = "farcaster_stats"
version = "1.0.2"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
substreams = "0.6"
substreams-ethereum = "0.10.6"
hex = "0.4"
prost = "0.13"

[build-dependencies]
tonic-build = "0.10" 