// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FarcasterEvents {
    #[prost(message, repeated, tag="1")]
    pub user_registrations: ::prost::alloc::vec::Vec<UserRegistration>,
    #[prost(message, repeated, tag="2")]
    pub storage_events: ::prost::alloc::vec::Vec<StorageEvent>,
    #[prost(message, repeated, tag="3")]
    pub key_changes: ::prost::alloc::vec::Vec<KeyChange>,
    #[prost(uint64, tag="4")]
    pub total_events: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserRegistration {
    #[prost(string, tag="1")]
    pub farcaster_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub ethereum_address: ::prost::alloc::string::String,
    #[prost(uint64, tag="3")]
    pub block_number: u64,
    #[prost(string, tag="4")]
    pub transaction_hash: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StorageEvent {
    #[prost(string, tag="1")]
    pub farcaster_id: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub storage_units: u32,
    #[prost(string, tag="3")]
    pub event_type: ::prost::alloc::string::String,
    #[prost(uint64, tag="4")]
    pub block_number: u64,
    #[prost(string, tag="5")]
    pub transaction_hash: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KeyChange {
    #[prost(string, tag="1")]
    pub farcaster_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub key_type: ::prost::alloc::string::String,
    #[prost(uint64, tag="3")]
    pub block_number: u64,
    #[prost(string, tag="4")]
    pub transaction_hash: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
